# Generated by Django 5.0.1 on 2024-02-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoadm',
            name='nome_contribuinte',
            field=models.CharField(max_length=100),
        ),
    ]
