# Generated by Django 5.0.1 on 2024-02-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0003_municipioadm_brasao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipioadm',
            name='brasao',
            field=models.ImageField(upload_to='brasoes/'),
        ),
        migrations.AlterField(
            model_name='processoadm',
            name='uf',
            field=models.CharField(choices=[('MS', 'MS')], max_length=2),
        ),
    ]
