# Generated by Django 5.0.1 on 2024-02-14 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0004_alter_municipioadm_brasao_alter_processoadm_uf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andamentoadm',
            name='complemento',
        ),
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data_criação')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Alterado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('assunto', models.CharField(max_length=100)),
                ('usuario_criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='andamentoadm',
            name='assunto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='processo.assunto'),
        ),
    ]
