# Generated by Django 5.0.1 on 2024-02-14 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0005_remove_andamentoadm_complemento_assunto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andamentoadm',
            name='assunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processo.assunto'),
        ),
    ]
