# Generated by Django 5.0.1 on 2024-02-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0006_alter_andamentoadm_assunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipioadm',
            name='brasao',
            field=models.ImageField(blank=True, null=True, upload_to='brasoes/'),
        ),
    ]
