# Generated by Django 5.0.1 on 2024-02-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0008_alter_municipioadm_brasao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipioadm',
            name='brasao',
            field=models.ImageField(null=True, upload_to='brasoes/'),
        ),
    ]
