# Generated by Django 5.0.1 on 2024-02-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0012_alter_processoadm_documento_alter_processoadm_uf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='andamentoadm',
            old_name='arquivo',
            new_name='arquivo1',
        ),
        migrations.AddField(
            model_name='andamentoadm',
            name='arquivo2',
            field=models.FileField(blank=True, upload_to='arquivo/', verbose_name='Arquivo'),
        ),
        migrations.AddField(
            model_name='andamentoadm',
            name='arquivo3',
            field=models.FileField(blank=True, upload_to='arquivo/', verbose_name='Arquivo'),
        ),
    ]
