# Generated by Django 5.0.1 on 2024-02-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0002_alter_processoadm_nome_contribuinte'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipioadm',
            name='brasao',
            field=models.ImageField(default='caminho/vazio', upload_to='imagens/'),
            preserve_default=False,
        ),
    ]
