# Generated by Django 5.0.1 on 2024-02-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0007_alter_municipioadm_brasao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipioadm',
            name='brasao',
            field=models.ImageField(default=1, upload_to='brasoes/'),
            preserve_default=False,
        ),
    ]
