# Generated by Django 5.0.1 on 2024-02-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0010_alter_municipioadm_brasao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoadm',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='N°'),
        ),
    ]
