# Generated by Django 5.0.1 on 2024-02-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0011_alter_processoadm_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoadm',
            name='documento',
            field=models.CharField(max_length=20, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='processoadm',
            name='uf',
            field=models.CharField(choices=[('MS', 'MS')], default='MS', max_length=2),
        ),
    ]
