# Generated by Django 5.0.1 on 2024-02-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0014_remove_andamentoadm_arquivo2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andamentoadm',
            name='arquivo1',
        ),
        migrations.AddField(
            model_name='andamentoadm',
            name='arquivo',
            field=models.FileField(blank=True, upload_to='arquivo/', verbose_name='Arquivo'),
        ),
    ]
